const images = {
    'diamonds_2': new URL('../assets/diamonds_2.svg', import.meta.url),
    'diamonds_3': new URL('../assets/diamonds_3.svg', import.meta.url),
    'diamonds_4': new URL('../assets/diamonds_4.svg', import.meta.url),
    'diamonds_5': new URL('../assets/diamonds_5.svg', import.meta.url),
    'diamonds_6': new URL('../assets/diamonds_6.svg', import.meta.url),
    'diamonds_7': new URL('../assets/diamonds_7.svg', import.meta.url),
    'diamonds_8': new URL('../assets/diamonds_8.svg', import.meta.url),
    'diamonds_9': new URL('../assets/diamonds_9.svg', import.meta.url),
    'diamonds_10': new URL('../assets/diamonds_10.svg', import.meta.url),
    'diamonds_jack': new URL('../assets/diamonds_jack.svg', import.meta.url),
    'diamonds_queen': new URL('../assets/diamonds_queen.svg', import.meta.url),
    'diamonds_king': new URL('../assets/diamonds_king.svg', import.meta.url),
    'diamonds_ace': new URL('../assets/diamonds_ace.svg', import.meta.url),
    'clubs_2': new URL('../assets/clubs_2.svg', import.meta.url),
    'clubs_3': new URL('../assets/clubs_3.svg', import.meta.url),
    'clubs_4': new URL('../assets/clubs_4.svg', import.meta.url),
    'clubs_5': new URL('../assets/clubs_5.svg', import.meta.url),
    'clubs_6': new URL('../assets/clubs_6.svg', import.meta.url),
    'clubs_7': new URL('../assets/clubs_7.svg', import.meta.url),
    'clubs_8': new URL('../assets/clubs_8.svg', import.meta.url),
    'clubs_9': new URL('../assets/clubs_9.svg', import.meta.url),
    'clubs_10': new URL('../assets/clubs_10.svg', import.meta.url),
    'clubs_jack': new URL('../assets/clubs_jack.svg', import.meta.url),
    'clubs_queen': new URL('../assets/clubs_queen.svg', import.meta.url),
    'clubs_king': new URL('../assets/clubs_king.svg', import.meta.url),
    'clubs_ace': new URL('../assets/clubs_ace.svg', import.meta.url),
    'spades_2': new URL('../assets/spades_2.svg', import.meta.url),
    'spades_3': new URL('../assets/spades_3.svg', import.meta.url),
    'spades_4': new URL('../assets/spades_4.svg', import.meta.url),
    'spades_5': new URL('../assets/spades_5.svg', import.meta.url),
    'spades_6': new URL('../assets/spades_6.svg', import.meta.url),
    'spades_7': new URL('../assets/spades_7.svg', import.meta.url),
    'spades_8': new URL('../assets/spades_8.svg', import.meta.url),
    'spades_9': new URL('../assets/spades_9.svg', import.meta.url),
    'spades_10': new URL('../assets/spades_10.svg', import.meta.url),
    'spades_jack': new URL('../assets/spades_jack.svg', import.meta.url),
    'spades_queen': new URL('../assets/spades_queen.svg', import.meta.url),
    'spades_king': new URL('../assets/spades_king.svg', import.meta.url),
    'spades_ace': new URL('../assets/spades_ace.svg', import.meta.url),
    'hearts_2' : new URL('../assets/hearts_2.svg', import.meta.url),
    'hearts_3' : new URL('../assets/hearts_3.svg', import.meta.url),
    'hearts_4' : new URL('../assets/hearts_4.svg', import.meta.url),
    'hearts_5' : new URL('../assets/hearts_5.svg', import.meta.url),
    'hearts_6' : new URL('../assets/hearts_6.svg', import.meta.url),
    'hearts_7' : new URL('../assets/hearts_7.svg', import.meta.url),
    'hearts_8' : new URL('../assets/hearts_8.svg', import.meta.url),
    'hearts_9' : new URL('../assets/hearts_9.svg', import.meta.url),
    'hearts_10' : new URL('../assets/hearts_10.svg', import.meta.url),
    'hearts_jack' : new URL('../assets/hearts_jack.svg', import.meta.url),
    'hearts_queen' : new URL('../assets/hearts_queen.svg', import.meta.url),
    'hearts_king' : new URL('../assets/hearts_king.svg', import.meta.url),
    'hearts_ace' : new URL('../assets/hearts_ace.svg', import.meta.url)
}

export default images;